Fix release action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -68,8 +68,6 @@ jobs:
       TARGET_DIR: ./target
       # Emit backtraces on panics.
       RUST_BACKTRACE: 1
-      # Build static releases with PCRE2.
-      PCRE2_SYS_STATIC: 1
     strategy:
       matrix:
         build: [linux, macos, win-msvc]
@@ -96,12 +94,8 @@ jobs:
     - name: Install packages (Ubuntu)
       if: matrix.os == 'ubuntu-18.04'
       run: |
-        ci/ubuntu-install-packages
-
-    - name: Install packages (macOS)
-      if: matrix.os == 'macos-latest'
-      run: |
-        ci/macos-install-packages
+        sudo apt-get update
+        sudo apt-get install -y --no-install-recommends liblz4-tool musl-tools
 
     - name: Install Rust
       uses: actions-rs/toolchain@v1
@@ -126,29 +120,30 @@ jobs:
         echo "target dir is: ${{ env.TARGET_DIR }}"
 
     - name: Build release binary
-      run: ${{ env.CARGO }} build --verbose --release --features pcre2 ${{ env.TARGET_FLAGS }}
+      # include --verbose if this is giving trouble
+      run: ${{ env.CARGO }} build --release ${{ env.TARGET_FLAGS }}
 
     - name: Build archive
       shell: bash
       run: |
         if [ "${{ matrix.os }}" = "windows-2019" ]; then
           staging="twittier-${{ needs.create-release.outputs.tw_version }}-windows"
-        elif [ "$os" = "ubuntu-18.04" ]; then
+        elif [ "${{ matrix.os }}" = "ubuntu-18.04" ]; then
           staging="twittier-${{ needs.create-release.outputs.tw_version }}-linux"
         else
           staging="twittier-${{ needs.create-release.outputs.tw_version }}-mac"
         fi
         mkdir -p "$staging"
 
-        cp {LICENSE} "$staging/"
+        cp LICENSE "$staging/" || echo "failed to add license to archive, no biggie"
 
         if [ "${{ matrix.os }}" = "windows-2019" ]; then
           cp "target/${{ matrix.target }}/release/tw.exe" "$staging/"
           7z a "$staging.zip" "$staging"
           echo "ASSET=$staging.zip" >> $GITHUB_ENV
         else
-          cp "target/${{ matrix.target }}/release/tw" "$staging/"
-          zip "$staging.zip" "$staging"
+          cp "target/${{ matrix.target }}/release/tw" "$staging"
+          zip -r "$staging.zip" "$staging"
           echo "ASSET=$staging.zip" >> $GITHUB_ENV
         fi
 
